name: amyb_detection
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  #- _libgcc_mutex=0.1
  #- _openmp_mutex=5.1
  - alsa-lib=1.2.3.2
  - arrow=1.3.0
  - asttokens=2.2.1
  - atk-1.0=2.36.0
  - backcall=0.2.0
  - backoff=2.2.1
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.12.3
  - binutils_impl_linux-64=2.38
  - blas=1.0
  - blessed=1.19.1
  - blosc=1.21.1
  - boost-cpp=1.74.0
  - boto3=1.34.90
  - botocore=1.34.91
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2024.2.2
  - cairo=1.16.0
  - certifi=2024.2.2
  - cffi=1.15.0
  - cfitsio=3.470
  - charls=2.2.0
  - charset-normalizer=2.0.4
  - click=8.0.4
  - cloudpickle=2.0.0
  - colorama=0.4.6
  - croniter=1.4.1
  - cryptography=37.0.1
  - cuda-cudart=11.7.99
  - cuda-cupti=11.7.101
  - cuda-libraries=11.7.1
  - cuda-nvrtc=11.7.99
  - cuda-nvtx=11.7.91
  - cuda-runtime=11.7.1
  - cudatoolkit=10.2.89
  - curl=7.82.0
  - cycler=0.11.0
  - cython=0.29.32
  - cytoolz=0.11.0
  - dask-core=2022.5.0
  - dateutils=0.6.12
  - dbus=1.13.18
  - debugpy=1.5.1
  - decorator=5.1.1
  - deepdiff=6.2.2
  - docker-pycreds=0.4.0
  - entrypoints=0.4
  - executing=1.2.0
  - expat=2.4.8
  - ffmpeg=4.3.2
  - fftw=3.3.10
  - filelock=3.9.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.0
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.25.0
  - freetype=2.11.0
  - freexl=1.0.6
  - fribidi=1.0.10
  - future=0.18.2
  - g-ir-build-tools=1.68.0
  - g-ir-host-tools=1.68.0
  - gcc=11.2.0
  - gcc_impl_linux-64=11.2.0
  #- gdk-pixbuf=2.42.6
  - geos=3.9.1
  - geotiff=1.6.0
  - gettext=0.21.0
  - ghostscript=9.54.0
  - giflib=5.2.1
  - gitdb=4.0.7
  - gitpython=3.1.18
  - glib=2.68.4
  - glib-tools=2.68.4
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - gobject-introspection=1.68.0
  - grad-cam=1.3.9
  - graphite2=1.3.14
  - graphviz=2.49.0
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - gstreamer-orc=0.4.32
  - gtk2=2.24.33
  - gts=0.7.6
  - h11=0.14.0
  - harfbuzz=2.9.1
  - hdf4=4.2.15
  - hdf5=1.10.6
  - huggingface_hub=0.17.3
  - icu=68.1
  - idna=3.3
  - imagecodecs=2021.7.30
  - imageio=2.34.0
  - imagemagick=7.1.0_8
  - importlib-metadata=6.1.0
  - inquirer=3.1.4
  - intel-openmp=2021.4.0
  - ipykernel=6.15.0
  - ipython=8.10.0
  - itsdangerous=2.2.0
  - jasper=1.900.1
  - jbig=2.1
  - jedi=0.18.2
  - jinja2=3.1.2
  - jmespath=1.0.1
  - joblib=1.2.0
  - jpeg=9e
  - json-c=0.15
  - jupyter_client=7.0.6
  - jupyter_core=4.12.0
  - jxrlib=1.1
  - kealib=1.4.14
  - kernel-headers_linux-64=2.6.32
  - keyutils=1.6.1
  - kiwisolver=1.4.2
  - krb5=1.19.2
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=2.2.1
  - libaec=1.0.6
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=11.1.0
  - libcublas=11.10.3.66
  - libcufft=10.7.2.124
  - libcufile=1.6.0.25
  - libcurand=10.3.2.56
  - libcurl=7.82.0
  - libcusolver=11.4.0.1
  - libcusparse=11.7.4.91
  - libdap4=3.20.6
  - libdeflate=1.7
  - libedit=3.1.20210910
  - libev=4.33
  - libevent=2.1.10
  - libexif=0.6.21
  - libffi=3.3
  - libgcc-devel_linux-64=11.2.0
  - libgcc-ng=11.2.0
  - libgd=2.3.3
  - libgdal=3.2.2
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgirepository=1.68.0
  - libglib=2.68.4
  - libgomp=11.2.0
  - libgsf=1.14.47
  - libiconv=1.16
  - libidn2=2.3.2
  - libkml=1.3.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm11=11.1.0
  - libmatio=1.5.21
  - libnetcdf=4.8.1
  - libnghttp2=1.46.0
  - libnpp=11.7.4.75
  - libnsl=2.0.0
  - libnvjpeg=11.8.0.2
  - libogg=1.3.5
  - libopencv=4.5.3
  - libopus=1.3.1
  - libpng=1.6.37
  - libpq=13.3
  - libprotobuf=3.16.0
  - librsvg=2.52.2
  - librttopo=1.1.0
  - libsodium=1.0.18
  - libspatialite=5.0.1
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtasn1=4.16.0
  - libtiff=4.3.0
  - libtool=2.4.6
  - libunistring=0.9.10
  - libuuid=2.32.1
  - libvips=8.11.4
  - libvorbis=1.3.7
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.15
  - libxkbcommon=1.0.3
  - libxml2=2.9.12
  - libzip=1.8.0
  - libzopfli=1.0.3
  - lightning=2.1.2
  - lightning-cloud=0.5.68
  - locket=1.0.0
  - lz4-c=1.9.3
  - magma=2.5.4
  - markdown-it-py=3.0.0
  - markupsafe=2.1.1
  - matplotlib=3.5.2
  - matplotlib-base=3.5.2
  - matplotlib-inline=0.1.6
  - mdurl=0.1.2
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.2.1
  - munch=2.5.0
  - munkres=1.1.4
  - mysql-common=8.0.25
  - mysql-libs=8.0.25
  - nccl=2.12.12.1
  - ncurses=6.3
  - nest-asyncio=1.5.6
  - nettle=3.7.3
  - networkx=2.7.1
  - ninja=1.10.2
  - ninja-base=1.10.2
  - nspr=4.33
  - nss=3.74
  - numexpr=2.8.3
  - numpy=1.22.3
  - numpy-base=1.22.3
  - opencv=4.5.3
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openslide=3.4.1
  - openssl=1.1.1o
  - ordered-set=4.1.0
  - packaging=21.3
  - pandas=1.4.4
  - pango=1.48.10
  - parso=0.8.3
  - partd=1.2.0
  - pathtools=0.1.2
  - pcre=8.45
  - perl=5.32.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.0.1
  - pip=21.2.4
  - pixman=0.40.0
  - pkg-config=0.29.2
  - plotly=5.13.0
  - poppler=21.09.0
  - poppler-data=0.4.11
  - postgresql=13.3
  - pretrainedmodels=0.7.4
  - proj=8.0.1
  - promise=2.3
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py-opencv=4.5.3
  - pycocotools=2.0.4
  - pycparser=2.21
  - pyfiglet=0.8.post1
  - pygments=2.14.0
  - pyjwt=2.8.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.4
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pysocks=1.7.1
  - python=3.9.7
  - python-dateutil=2.8.2
  - python-editor=1.0.4
  - python_abi=3.9
  - pytorch=2.0.0
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0
  - pytz=2022.1
  - pywavelets=1.3.0
  - pyyaml=6.0
  - pyzmq=19.0.2
  - qt=5.12.9
  - qudida=0.0.4
  - readchar=4.0.5
  - readline=8.1.2
  - requests=2.28.0
  - rich=13.7.1
  - s3transfer=0.10.1
  - safetensors=0.4.2
  - scikit-image=0.19.2
  - scipy=1.9.3
  - sentry-sdk=1.9.0
  - setproctitle=1.2.2
  - setuptools=61.2.0
  - shortuuid=1.0.10
  - six=1.16.0
  - sleef=3.5.1
  - smmap=4.0.0
  - snappy=1.1.9
  - soupsieve=2.5
  - sqlite=3.38.5
  - stack_data=0.6.2
  - starlette=0.27.0
  - starsessions=1.3.0
  - sympy=1.11.1
  - sysroot_linux-64=2.12
  - tenacity=8.0.1
  - threadpoolctl=3.1.0
  - tifffile=2020.10.1
  - tiledb=2.3.4
  - tk=8.6.12
  - toolz=0.11.2
  - torchaudio=2.0.0
  - torchtriton=2.0.0
  - torchvision=0.15.0
  - tornado=6.1
  - tqdm=4.64.0
  - traitlets=5.9.0
  - ttach=0.0.3
  - types-python-dateutil=2.9.0.20240316
  - typing_extensions=4.1.1
  - tzcode=2022a
  - tzdata=2022a
  - urllib3=1.26.9
  - wandb=0.13.5
  - wcwidth=0.2.6
  - wheel=0.37.1
  - x264=1!161.3030
  - xerces-c=3.2.3
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.2.1
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.4
  - zfp=0.5.5
  - zipp=3.15.0
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
      - absl-py==2.1.0
      - aiofiles==23.2.1
      - aiohttp==3.8.5
      - aiosignal==1.3.1
      - albumentations==1.3.0
      - altair==5.1.2
      - annotated-types==0.6.0
      - anyio==3.7.1
      - async-timeout==4.0.3
      - attrs==23.1.0
      - centerline==1.1.0
      - click-plugins==1.1.1
      - cligj==0.7.2
      - config==0.5.1
      - cupy-cuda11x==13.0.0
      - efficientnet-pytorch==0.7.1
      - et-xmlfile==1.1.0
      - exceptiongroup==1.1.3
      - fastapi==0.104.0
      - fastjsonschema==2.17.1
      - fastrlock==0.8.2
      - ffmpy==0.3.1
      - fiona==1.9.6
      - frozenlist==1.4.0
      - fsspec==2023.9.2
      - geojson==3.0.1
      #- gradio==3.49.0
      #- gradio-client==0.6.1
      - grpcio==1.62.2
      - httpcore==0.18.0
      - httpx==0.25.0
      - huggingface-hub==0.18.0
      - imgaug==0.4.0
      - importlib-resources==6.1.0
      - jsonpatch==1.33
      - jsonpointer==2.4
      - jsonschema==4.18.0
      - jsonschema-specifications==2023.6.1
      - lightning-utilities==0.9.0
      - llvmlite==0.41.1
      - lmdb==1.4.1
      - markdown==3.6
      - multidict==6.0.4
      - nbformat==5.9.1
      - numba==0.58.1
      - opencv-python==4.9.0.80
      - opencv-python-headless==4.7.0.68
      - openpyxl==3.1.2
      #- openslide-python==1.2.0
      - orjson==3.9.9
      - patsy==0.5.6
      - protobuf==3.16.0
      - pydantic==2.4.2
      - pydantic-core==2.10.1
      - pydub==0.25.1
      - python-multipart==0.0.6
      - pytorch-lightning==2.0.7
      - pyvips==2.2.1
      - referencing==0.29.1
      - rpds-py==0.8.10
      - scikit-learn==1.1.3
      - seaborn==0.12.2
      - segmentation-models-pytorch==0.3.2
      - semantic-version==2.10.0
      - shapely==2.0.3
      - sniffio==1.3.0
      - statsmodels==0.14.2
      - tensorboard-data-server==0.7.2
      - timm==0.6.12
      - torchdata==0.6.0
      - torchmetrics==1.0.1
      - typing==3.7.4.3
      - typing-extensions==4.8.0
      - uvicorn==0.23.2
      - visdom==0.2.4
      - websocket-client==1.7.0
      - websockets==11.0.3
      - werkzeug==3.0.2
      - yarl==1.9.2
